package com.wenld.downloadutils.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import java.io.Serializable;

/**
 * Entity mapped to table "THREAD_INFO".
 */
public class ThreadInfo implements Serializable {

    private String id;
    /** Not-null value. */
    private String fileId;
    /** Not-null value. */
    private String url;
    /** Not-null value. */
    private String md5;
    private int finished;
    private String rate;
    private Boolean over;
    private String overtime;
    private Integer start;
    private Integer end;

    public ThreadInfo() {
    }

    public ThreadInfo(String id) {
        this.id = id;
    }

    public ThreadInfo(String id, String fileId, String url, String md5, int finished, String rate, Boolean over, String overtime, Integer start, Integer end) {
        this.id = id;
        this.fileId = fileId;
        this.url = url;
        this.md5 = md5;
        this.finished = finished;
        this.rate = rate;
        this.over = over;
        this.overtime = overtime;
        this.start = start;
        this.end = end;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getFileId() {
        return fileId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFileId(String fileId) {
        this.fileId = fileId;
    }

    /** Not-null value. */
    public String getUrl() {
        return url;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUrl(String url) {
        this.url = url;
    }

    /** Not-null value. */
    public String getMd5() {
        return md5;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setMd5(String md5) {
        this.md5 = md5;
    }

    public int getFinished() {
        return finished;
    }

    public void setFinished(int finished) {
        this.finished = finished;
    }

    public String getRate() {
        return rate;
    }

    public void setRate(String rate) {
        this.rate = rate;
    }

    public Boolean getOver() {
        return over;
    }

    public void setOver(Boolean over) {
        this.over = over;
    }

    public String getOvertime() {
        return overtime;
    }

    public void setOvertime(String overtime) {
        this.overtime = overtime;
    }

    public Integer getStart() {
        return start;
    }

    public void setStart(Integer start) {
        this.start = start;
    }

    public Integer getEnd() {
        return end;
    }

    public void setEnd(Integer end) {
        this.end = end;
    }

}
